/**
 * Provides the classes necessary to create a parser application using XML2J.
 * <p>
 * This class is used as the base class for the (optionally) generated parser application class.
 * The Application class ties the Reader and Processor component together. It is generated by setting the 
 * interface message-handler-application attribute. The processor is given by the message-handler-processor attribute.
 *
 * @since 2.1
 * @version 2.4
 * @see com.xml2j.xml.core
 */
package com.xml2j.xml.parser;